/**
 * 錯誤碼 ↔ HTTP status 對照與工廠方法
 */
const AppError = require("./AppError");
const C = require("../apiErrorCodes");

/** @type {Record<string, number>} */
const STATUS_BY_CODE = {
  [C.INTERNAL_ERROR]: 500,
  [C.BAD_REQUEST]: 400,
  [C.NOT_FOUND]: 404,
  [C.FORBIDDEN]: 403,
  [C.CONFLICT]: 409,
  [C.SERVICE_UNAVAILABLE]: 503,
  [C.BAD_GATEWAY]: 502,

  [C.AUTH_TOKEN_MISSING]: 401,
  [C.AUTH_TOKEN_INVALID]: 401,
  [C.AUTH_TOKEN_REVOKED]: 401,
  [C.AUTH_FAILED]: 401,
  [C.RATE_LIMIT_EXCEEDED]: 429,
  [C.AUTH_UNAUTHENTICATED]: 401,
  [C.AUTH_CONTEXT_MISSING]: 401,
  [C.PERMISSION_DENIED]: 403,
  [C.PERMISSION_LOAD_FAILED]: 500,
  [C.FEATURE_NOT_LICENSED]: 403,
  [C.LICENSE_CHECK_FAILED]: 503,
  [C.LICENSE_QUOTA_EXCEEDED]: 403,

  [C.LICENSE_PLATFORM_ERROR]: 502,
  [C.LICENSE_PLATFORM_INVALID_RESPONSE]: 502,
  [C.LICENSE_ALREADY_USED]: 403,
  [C.LICENSE_INACTIVE]: 403,
  [C.LICENSE_SIGN_SECRET_MISSING]: 500,
  [C.INVALID_LICENSE_PAYLOAD]: 400,
  [C.INVALID_OFFLINE_LICENSE_SIGNATURE]: 403,
  [C.INVALID_LICENSE_PRODUCT]: 400,

  [C.VALIDATION_REQUIRED]: 400,
  [C.VALIDATION_INVALID_NUMBER]: 400,
  [C.VALIDATION_INVALID_INTEGER]: 400,
  [C.VALIDATION_INVALID_ENUM]: 400,
  [C.VALIDATION_INVALID_DATE]: 400,
  [C.VALIDATION_CUSTOM]: 400,

  [C.EXTERNAL_DATA_TABLE_FORBIDDEN]: 403,
  [C.EXTERNAL_DATA_HANDLER_NOT_FOUND]: 404,
  [C.EXTERNAL_DATA_SYSTEM_NOT_FOUND]: 404,
  [C.EXTERNAL_DATA_RECORD_NOT_FOUND]: 404,
  [C.EXTERNAL_DATA_PICTURE_FAILED]: 500,
  [C.EXTERNAL_DATA_INVALID_PIC_URIS]: 400,

  [C.SETTINGS_KEY_NOT_FOUND]: 404,
  [C.SETTINGS_KEY_REQUIRED]: 400,
  [C.SETTINGS_INVALID_BATCH_KEYS]: 400,
  [C.SETTINGS_UPLOAD_FILE_MISSING]: 400,
  [C.SETTINGS_UPLOAD_KEY_MISSING]: 400,
  [C.MULTIMEDIA_UPLOAD_FILE_MISSING]: 400,
  [C.SMOKE_ALARM_MESSAGE_REQUIRED]: 400,

  [C.MODBUS_INVALID_REQUESTS]: 400,
  [C.MODBUS_REQUESTS_TOO_LARGE]: 400,
  [C.MODBUS_INVALID_ADDRESS]: 400,
  [C.MODBUS_INVALID_VALUES]: 400,
  [C.MODBUS_INVALID_BODY]: 400,

  [C.ALERT_RULE_NOT_FOUND]: 404,
  [C.ALERT_VALIDATION_FAILED]: 400,
  [C.ALERT_SMTP_INVALID]: 400,
  [C.ALERT_SMTP_SEND_FAILED]: 502,

  [C.DEVICE_NOT_FOUND]: 404,
  [C.DEVICE_NOT_CAMERA]: 400,
  [C.DEVICE_RTSP_URL_MISSING]: 400,
  [C.DEVICE_UNSUPPORTED_FEATURE]: 400,
  [C.DEVICE_NAME_REQUIRED]: 400,
  [C.DEVICE_NAME_TOO_LONG]: 400,
  [C.DEVICE_TYPE_REQUIRED]: 400,
  [C.DEVICE_TYPE_INVALID]: 400,
  [C.DEVICE_CONFIG_REQUIRED]: 400,
  [C.DEVICE_MODEL_ID_REQUIRED]: 400,
  [C.DEVICE_MODEL_NOT_FOUND]: 404,
  [C.DEVICE_MODEL_TYPE_MISMATCH]: 400,
  [C.DEVICE_LOGGING_CONFIG_INVALID]: 400,
  [C.DEVICE_CONTROLLER_HOST_REQUIRED]: 400,
  [C.DEVICE_CONTROLLER_PORT_REQUIRED]: 400,
  [C.DEVICE_SENSOR_HOST_REQUIRED]: 400,
  [C.DEVICE_SENSOR_PORT_REQUIRED]: 400,
  [C.DEVICE_UNIT_ID_EXHAUSTED]: 400,
  [C.DEVICE_DUPLICATE_CONNECTION]: 409,
  [C.DEVICE_UPDATE_NO_FIELDS]: 400,
  [C.DEVICE_LIST_FAILED]: 500,
  [C.DEVICE_GET_FAILED]: 500,
  [C.DEVICE_CREATE_FAILED]: 500,
  [C.DEVICE_UPDATE_FAILED]: 500,
  [C.DEVICE_DELETE_FAILED]: 500,
  [C.DEVICE_CAMERA_GROUPS_FAILED]: 500,
  [C.DEVICE_CONFIG_INVALID]: 400,

  [C.DEVICE_MODEL_NAME_REQUIRED]: 400,
  [C.DEVICE_MODEL_PORT_INVALID]: 400,
  [C.DEVICE_MODEL_UNIT_ID_INVALID]: 400,
  [C.DEVICE_MODEL_SENSOR_PARAMETERS_INVALID]: 400,
  [C.DEVICE_MODEL_REGISTER_TYPE_INVALID]: 400,
  [C.DEVICE_MODEL_CATEGORY_CODE_INVALID]: 400,
  [C.DEVICE_MODEL_TYPE_CHANGE_FORBIDDEN]: 409,
  [C.DEVICE_MODEL_IN_USE]: 409,
  [C.DEVICE_MODEL_UPDATE_NO_FIELDS]: 400,
  [C.DEVICE_MODEL_LIST_FAILED]: 500,
  [C.DEVICE_MODEL_GET_FAILED]: 500,
  [C.DEVICE_MODEL_CREATE_FAILED]: 500,
  [C.DEVICE_MODEL_UPDATE_FAILED]: 500,
  [C.DEVICE_MODEL_DELETE_FAILED]: 500,

  [C.DEVICE_CONNECTIVITY_RTSP_URL_INVALID]: 400,
  [C.DEVICE_CONNECTIVITY_RTSP_TIMEOUT]: 503,
  [C.DEVICE_CONNECTIVITY_RTSP_FAILED]: 503,
  [C.DEVICE_CONNECTIVITY_RTSP_RESPONSE_INVALID]: 503,
  [C.DEVICE_CONNECTIVITY_MODBUS_CONFIG_INCOMPLETE]: 400,
  [C.DEVICE_CONNECTIVITY_MODBUS_FAILED]: 503,
  [C.DEVICE_CONNECTIVITY_TCP_CONFIG_INCOMPLETE]: 400,
  [C.DEVICE_CONNECTIVITY_TCP_TIMEOUT]: 503,
  [C.DEVICE_CONNECTIVITY_TCP_FAILED]: 503,
  [C.DEVICE_CONNECTIVITY_ISAPI_CONFIG_INCOMPLETE]: 400,
  [C.DEVICE_CONNECTIVITY_ISAPI_TIMEOUT]: 503,
  [C.DEVICE_CONNECTIVITY_CAMERA_RTSP_MISSING]: 400,
  [C.DEVICE_CONNECTIVITY_DEVICE_ID_INVALID]: 400,

  [C.MODBUS_DEVICE_CONFIG_REQUIRED]: 400,
  [C.MODBUS_REGISTER_TYPE_UNSUPPORTED]: 400,
  [C.MODBUS_CONNECTION_CLOSED]: 503,
  [C.MODBUS_CONNECTION_INTERRUPTED]: 503,
  [C.MODBUS_CONNECTION_TIMEOUT]: 503,
  [C.MODBUS_CONNECTION_REFUSED]: 503,
  [C.MODBUS_CONNECTION_UNREACHABLE]: 503,
  [C.MODBUS_CONNECTION_FAILED]: 503,
  [C.MODBUS_READ_TIMEOUT]: 503,
  [C.MODBUS_WRITE_TIMEOUT]: 503,
  [C.MODBUS_HOST_REQUIRED]: 400,
  [C.MODBUS_PORT_REQUIRED]: 400,
  [C.MODBUS_UNIT_ID_REQUIRED]: 400,
  [C.MODBUS_INVALID_LENGTH]: 400,

  [C.ACCESS_CONTROL_NOT_DEVICE]: 400,
  [C.ACCESS_CONTROL_CONFIG_INCOMPLETE]: 400,
  [C.ACCESS_CONTROL_ISAPI_INVALID_RESPONSE]: 502,
  [C.ACCESS_CONTROL_EMPLOYEE_NO_REQUIRED]: 400,
  [C.ACCESS_CONTROL_CARD_NO_REQUIRED]: 400,
  [C.ACCESS_CONTROL_FINGER_DATA_REQUIRED]: 400,
  [C.ACCESS_CONTROL_FACE_IMAGE_REQUIRED]: 400,
  [C.ACCESS_CONTROL_ABORTED]: 503,

  [C.LADDER_SDK_ERROR]: 502,
  [C.LADDER_SDK_BRIDGE_NOT_FOUND]: 503,
  [C.LADDER_SDK_RUNTIME_MISSING]: 503,
  [C.LADDER_SDK_BRIDGE_FAILED]: 502,
  [C.LADDER_SDK_TIMEOUT]: 504,
  [C.LADDER_SDK_NOT_DEVICE]: 400,
  [C.LADDER_SDK_CONFIG_INCOMPLETE]: 400,
  [C.LADDER_SDK_INVALID_COMMAND]: 400,
  [C.LADDER_SDK_INVALID_GATEWAY]: 400,
  [C.LADDER_SDK_LOGIN_FAILED]: 502,
  [C.LADDER_SDK_CARD_NOT_FOUND]: 404,
  [C.LADDER_SDK_CARD_READ_FAILED]: 502,
  [C.LADDER_SDK_CARD_WRITE_FAILED]: 502,
  [C.LADDER_SDK_CONTROL_FAILED]: 502,

  [C.VEHICLE_ACCESS_NOT_CAMERA]: 400,
  [C.VEHICLE_ACCESS_CONFIG_INCOMPLETE]: 400,
  [C.VEHICLE_ACCESS_ISAPI_INVALID_RESPONSE]: 502,
  [C.VEHICLE_ACCESS_DEVICE_NOT_IN_SITE]: 400,
  [C.VEHICLE_ACCESS_VALIDATION_FAILED]: 400,
  [C.PLATE_ALREADY_ASSIGNED]: 409,

  [C.ELEVATOR_VALIDATION_FAILED]: 400,
  [C.ELEVATOR_OPERATION_FAILED]: 500,
  [C.ELEVATOR_FLOOR_SYNC_FAILED]: 500,
  [C.ELEVATOR_SYNC_JOB_NOT_FOUND]: 404,

  [C.LOCATION_ZONE_NOT_FOUND]: 404,
  [C.LOCATION_ZONE_NAME_REQUIRED]: 400,
  [C.LOCATION_ZONE_NAME_TOO_LONG]: 400,
  [C.LOCATION_ZONE_NAME_DUPLICATE]: 409,
  [C.LOCATION_ZONE_LIST_FAILED]: 500,
  [C.LOCATION_ZONE_GET_FAILED]: 500,
  [C.LOCATION_ZONE_CREATE_FAILED]: 500,
  [C.LOCATION_ZONE_UPDATE_FAILED]: 500,
  [C.LOCATION_ZONE_DELETE_FAILED]: 500,
  [C.LOCATION_ZONE_DELETE_FORBIDDEN]: 400,

  [C.LOCATION_NOT_FOUND]: 404,
  [C.LOCATION_NAME_REQUIRED]: 400,
  [C.LOCATION_NAME_TOO_LONG]: 400,
  [C.LOCATION_NAME_DUPLICATE]: 409,
  [C.LOCATION_GET_FAILED]: 500,
  [C.LOCATION_CREATE_FAILED]: 500,
  [C.LOCATION_UPDATE_FAILED]: 500,
  [C.LOCATION_DELETE_FAILED]: 500,

  [C.LOCATION_SYSTEM_TYPE_REQUIRED]: 400,
  [C.LOCATION_SYSTEM_TYPE_INVALID]: 400,
  [C.LOCATION_SYSTEM_TYPE_DUPLICATE]: 409,
  [C.LOCATION_SYSTEM_NOT_FOUND]: 404,
  [C.LOCATION_DEVICE_NOT_FOUND]: 400,
  [C.LOCATION_DEVICE_NOT_CONTROLLER]: 400,

  [C.PERSONNEL_VALIDATION_FAILED]: 400,
  [C.PERSONNEL_PERSON_GROUP_NOT_FOUND]: 404,
  [C.PERSONNEL_PERSON_NOT_FOUND]: 404,
  [C.PERSONNEL_FACE_UPLOAD_FILE_MISSING]: 400,
  [C.PERSONNEL_FACE_UPLOAD_INVALID_FILE_FORMAT]: 400,
  [C.PERSONNEL_FACE_UPLOAD_VALIDATION_FAILED]: 400,
  [C.PERSONNEL_IMPORT_EXCEL_FILE_MISSING]: 400,
  [C.PERSONNEL_IMPORT_VALIDATION_FAILED]: 400,
  [C.PERSONNEL_SYNC_JOB_NOT_FOUND]: 404,
  [C.PERSONNEL_SYNC_JOB_VALIDATION_FAILED]: 400,
  [C.PERSONNEL_SYNC_UNKNOWN_STEP]: 400,
  [C.PERSONNEL_SYNC_JOB_INVALID_REQUEST]: 400,

  [C.USER_ROLE_INVALID]: 400,
  [C.USER_STATUS_INVALID]: 400,
  [C.USER_CREDENTIALS_REQUIRED]: 400,
  [C.USER_PASSWORD_TOO_SHORT]: 400,
  [C.USER_USERNAME_EXISTS]: 409,
  [C.USER_USERNAME_TAKEN]: 409,
  [C.USER_AUTH_FAILED]: 401,
  [C.USER_ACCOUNT_INACTIVE]: 403,
  [C.USER_NOT_FOUND]: 404,
  [C.USER_FORBIDDEN_ROLE_STATUS]: 403,
  [C.USER_FORBIDDEN_UPDATE_OTHERS]: 403,
  [C.USER_FORBIDDEN_PASSWORD_OTHERS]: 403,
  [C.USER_FORBIDDEN_PASSWORD_SELF]: 403,
  [C.USER_FORBIDDEN_PASSWORD_TARGET]: 403,
  [C.USER_OLD_PASSWORD_REQUIRED]: 400,
  [C.USER_FORBIDDEN_DELETE]: 403,
  [C.USER_FORBIDDEN_DELETE_SELF]: 400,
  [C.USER_FORBIDDEN_DELETE_ADMIN]: 403,
  [C.USER_OLD_PASSWORD_INVALID]: 400,

  [C.SETTINGS_LIST_FAILED]: 500,
  [C.SETTINGS_GET_FAILED]: 500,
  [C.SETTINGS_BATCH_GET_FAILED]: 500,
  [C.SETTINGS_UPSERT_FAILED]: 500,
  [C.SETTINGS_UPDATE_FAILED]: 500,
  [C.SETTINGS_DELETE_FAILED]: 500,

  [C.ENVIRONMENT_BUCKET_INVALID]: 400,
  [C.ENVIRONMENT_READINGS_LIST_FAILED]: 500,
  [C.ENVIRONMENT_READINGS_AGGREGATED_FAILED]: 500,
  [C.ENVIRONMENT_READING_REQUIRED]: 400,

  [C.PEOPLE_COUNTING_VALIDATION_FAILED]: 400,
  [C.PEOPLE_COUNTING_OPERATION_FAILED]: 500,

  [C.ALERT_NOT_FOUND]: 404,
  [C.ALERT_CREATE_VALIDATION_FAILED]: 400,
  [C.ALERT_STATUS_INVALID]: 400,
  [C.ALERT_OPERATION_FAILED]: 500,
  [C.ALERT_RULE_CREATE_FAILED]: 500,
  [C.ALERT_RULE_UPDATE_FAILED]: 500,
  [C.ALERT_LINKAGE_ID_INVALID]: 400,
  [C.ALERT_LINKAGE_RULE_ID_INVALID]: 400,
  [C.ALERT_LINKAGE_NOT_FOUND]: 404,
  [C.ALERT_LINKAGE_DO_TARGET_MISSING]: 400,
  [C.ALERT_SYSTEM_UNKNOWN]: 400,
  [C.ALERT_SYSTEM_SNAPSHOT_UNSUPPORTED]: 400,
  [C.ALERT_RULE_ALERT_TYPE_INVALID]: 400,
  [C.ALERT_RULE_BITKEY_INVALID]: 400,
  [C.ALERT_SOURCE_ID_NOT_FOUND]: 404,
  [C.ALERT_RULE_NOT_AVAILABLE]: 404,
  [C.ALERT_ERROR_TRACKER_UPSERT_FAILED]: 500,

  [C.SMTP_HOST_REQUIRED]: 400,
  [C.SMTP_PORT_REQUIRED]: 400,
  [C.SMTP_SECURITY_INVALID]: 400,

  [C.LICENSE_FEATURE_KEY_REQUIRED]: 500,
  [C.LICENSE_PLATFORM_API_BASE_URL_MISSING]: 500,
  [C.LICENSE_PLATFORM_LICENSE_KEY_REQUIRED]: 400,
  [C.LICENSE_PLATFORM_DEVICE_FINGERPRINT_REQUIRED]: 400,

  [C.MEDIAMTX_ADD_PATH_FAILED]: 502,
  [C.MEDIAMTX_ADD_PATH_REJECTED]: 400,
  [C.MEDIAMTX_REMOVE_PATH_FAILED]: 502,
  [C.MEDIAMTX_CONFIG_NOT_FOUND]: 500,

  [C.MONITOR_MODBUS_READ_FAILED]: 503,
  [C.MONITOR_TASK_INVALID]: 500,
  [C.MONITOR_FACTORY_CONFIG_INVALID]: 500,

  [C.EXTERNAL_DATA_QUERY_FAILED]: 500,
  [C.EXTERNAL_DATA_COUNT_FAILED]: 500,

  [C.ACCESS_CONTROL_ISAPI_DIGEST_CHALLENGE_EXPECTED]: 502,
  [C.ACCESS_CONTROL_ISAPI_AUTH_UNSUPPORTED]: 502,

  [C.BACKUP_DELETE_AFTER_SUCCESS_FAILED]: 500,

  [C.YSCP_FILE_NOT_FOUND]: 404,
  [C.YSCP_PERSON_INFO_FAILED]: 502,
  [C.YSCP_PERSON_PICTURE_FAILED]: 502,
  [C.YSCP_RESPONSE_PARSE_FAILED]: 502,

  [C.MULTIMEDIA_MODBUS_READ_FAILED]: 503,
};

/** @type {Record<number, string>} */
const CODE_BY_HTTP_STATUS = {
  400: C.BAD_REQUEST,
  401: C.AUTH_UNAUTHENTICATED,
  403: C.FORBIDDEN,
  404: C.NOT_FOUND,
  409: C.CONFLICT,
  502: C.BAD_GATEWAY,
  503: C.SERVICE_UNAVAILABLE,
  500: C.INTERNAL_ERROR,
};

function httpStatusForCode(code) {
  return STATUS_BY_CODE[code] ?? 500;
}

function codeForHttpStatus(statusCode) {
  return CODE_BY_HTTP_STATUS[statusCode] ?? C.INTERNAL_ERROR;
}

/**
 * @param {string} code
 * @param {string} message
 * @param {{ statusCode?: number, details?: unknown }} [options]
 */
function createApiError(code, message, options = {}) {
  const statusCode = options.statusCode ?? httpStatusForCode(code);
  return new AppError(message, {
    statusCode,
    code,
    details: options.details ?? null,
  });
}

function throwApiError(code, message, options = {}) {
  throw createApiError(code, message, options);
}

function rethrowIfApiError(error) {
  if (error?.statusCode || error?.code) {
    throw error;
  }
}

/** 服務層 catch：技術原因放 details.cause，message 保持簡短摘要 */
function causeDetails(error) {
  if (error == null) return null;
  if (typeof error === "string") return { cause: error };
  if (error instanceof Error && error.message) return { cause: error.message };
  if (typeof error === "object" && error.message) {
    return { cause: String(error.message) };
  }
  return { cause: String(error) };
}

module.exports = {
  httpStatusForCode,
  codeForHttpStatus,
  createApiError,
  throwApiError,
  rethrowIfApiError,
  causeDetails,
};
