/**
 * 即時／監控 Timing SSOT（後端）
 * 分層：Fast 1s｜電梯 idle 2s｜Standard 15s｜EVENT_COALESCE 500ms
 * @see docs/30-contracts/websocket.md
 */

const FAST_POLL_MS = 1000;
const STANDARD_POLL_MS = 15_000;

const ELEVATOR_POLL_IDLE_MS = 2000;
const ELEVATOR_POLL_MOVING_MS = 1000;
const ELEVATOR_ARRIVED_HOLD_MS = 1500;
const ELEVATOR_MOVING_TIMEOUT_MS = 60_000;
const ELEVATOR_LOCATION_CACHE_MS = 5_000;

const SOCKET_CONNECT_TIMEOUT_MS = 45_000;
const SOCKET_PING_INTERVAL_MS = 25_000;
const SOCKET_PING_TIMEOUT_MS = 20_000;
const DEVICE_STATUS_DEDUPE_TTL_MS = 2000;
const EVENT_COALESCE_MS = 500;

const DEVICE_CFG_TTL_MS = 60_000;
const MODBUS_BATCH_CACHE_TTL_MS = 800;
const CONNECTIVITY_TIMEOUT_MS = 5000;
const ENVIRONMENT_RAW_WRITE_INTERVAL_MS = 5 * 60 * 1000;
const ENVIRONMENT_READING_STALE_MS = 10 * 60 * 1000;
/** 能源表計：幾乎每 poll 寫 raw（利於差分） */
const ENERGY_RAW_WRITE_INTERVAL_MS = 15_000;
const ENERGY_READING_STALE_MS = 10 * 60 * 1000;

/** 固定間隔任務用：base = min = max */
const fixedIntervalOptions = (ms) => ({
  baseIntervalMs: ms,
  minIntervalMs: ms,
  maxIntervalMs: ms,
});

module.exports = {
  FAST_POLL_MS,
  STANDARD_POLL_MS,
  ELEVATOR_POLL_IDLE_MS,
  ELEVATOR_POLL_MOVING_MS,
  ELEVATOR_ARRIVED_HOLD_MS,
  ELEVATOR_MOVING_TIMEOUT_MS,
  ELEVATOR_LOCATION_CACHE_MS,
  SOCKET_CONNECT_TIMEOUT_MS,
  SOCKET_PING_INTERVAL_MS,
  SOCKET_PING_TIMEOUT_MS,
  DEVICE_STATUS_DEDUPE_TTL_MS,
  EVENT_COALESCE_MS,
  DEVICE_CFG_TTL_MS,
  MODBUS_BATCH_CACHE_TTL_MS,
  CONNECTIVITY_TIMEOUT_MS,
  ENVIRONMENT_RAW_WRITE_INTERVAL_MS,
  ENVIRONMENT_READING_STALE_MS,
  ENERGY_RAW_WRITE_INTERVAL_MS,
  ENERGY_READING_STALE_MS,
  fixedIntervalOptions,
};
