/**
 * 後端 API 錯誤碼常數（全專案 SSOT，禁止散落 magic string）
 */
module.exports = {
  // --- 通用 ---
  INTERNAL_ERROR: "INTERNAL_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  BAD_GATEWAY: "BAD_GATEWAY",

  // --- 認證／授權 ---
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_FAILED: "AUTH_FAILED",
  AUTH_UNAUTHENTICATED: "AUTH_UNAUTHENTICATED",
  AUTH_CONTEXT_MISSING: "AUTH_CONTEXT_MISSING",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  PERMISSION_LOAD_FAILED: "PERMISSION_LOAD_FAILED",
  FEATURE_NOT_LICENSED: "FEATURE_NOT_LICENSED",
  LICENSE_CHECK_FAILED: "LICENSE_CHECK_FAILED",
  LICENSE_QUOTA_EXCEEDED: "LICENSE_QUOTA_EXCEEDED",

  // --- License API ---
  LICENSE_PLATFORM_ERROR: "LICENSE_PLATFORM_ERROR",
  LICENSE_PLATFORM_INVALID_RESPONSE: "LICENSE_PLATFORM_INVALID_RESPONSE",
  LICENSE_ALREADY_USED: "LICENSE_ALREADY_USED",
  LICENSE_INACTIVE: "LICENSE_INACTIVE",
  LICENSE_SIGN_SECRET_MISSING: "LICENSE_SIGN_SECRET_MISSING",
  INVALID_LICENSE_PAYLOAD: "INVALID_LICENSE_PAYLOAD",
  INVALID_OFFLINE_LICENSE_SIGNATURE: "INVALID_OFFLINE_LICENSE_SIGNATURE",
  INVALID_LICENSE_PRODUCT: "INVALID_LICENSE_PRODUCT",

  // --- 驗證 ---
  VALIDATION_REQUIRED: "VALIDATION_REQUIRED",
  VALIDATION_INVALID_NUMBER: "VALIDATION_INVALID_NUMBER",
  VALIDATION_INVALID_INTEGER: "VALIDATION_INVALID_INTEGER",
  VALIDATION_INVALID_ENUM: "VALIDATION_INVALID_ENUM",
  VALIDATION_INVALID_DATE: "VALIDATION_INVALID_DATE",
  VALIDATION_CUSTOM: "VALIDATION_CUSTOM",

  // --- External data ---
  EXTERNAL_DATA_TABLE_FORBIDDEN: "EXTERNAL_DATA_TABLE_FORBIDDEN",
  EXTERNAL_DATA_HANDLER_NOT_FOUND: "EXTERNAL_DATA_HANDLER_NOT_FOUND",
  EXTERNAL_DATA_SYSTEM_NOT_FOUND: "EXTERNAL_DATA_SYSTEM_NOT_FOUND",
  EXTERNAL_DATA_RECORD_NOT_FOUND: "EXTERNAL_DATA_RECORD_NOT_FOUND",
  EXTERNAL_DATA_PICTURE_FAILED: "EXTERNAL_DATA_PICTURE_FAILED",
  EXTERNAL_DATA_INVALID_PIC_URIS: "EXTERNAL_DATA_INVALID_PIC_URIS",

  // --- Settings / multimedia / smoke ---
  SETTINGS_KEY_NOT_FOUND: "SETTINGS_KEY_NOT_FOUND",
  SETTINGS_KEY_REQUIRED: "SETTINGS_KEY_REQUIRED",
  SETTINGS_INVALID_BATCH_KEYS: "SETTINGS_INVALID_BATCH_KEYS",
  SETTINGS_UPLOAD_FILE_MISSING: "SETTINGS_UPLOAD_FILE_MISSING",
  SETTINGS_UPLOAD_KEY_MISSING: "SETTINGS_UPLOAD_KEY_MISSING",
  MULTIMEDIA_UPLOAD_FILE_MISSING: "MULTIMEDIA_UPLOAD_FILE_MISSING",
  SMOKE_ALARM_MESSAGE_REQUIRED: "SMOKE_ALARM_MESSAGE_REQUIRED",

  // --- Modbus ---
  MODBUS_INVALID_REQUESTS: "MODBUS_INVALID_REQUESTS",
  MODBUS_REQUESTS_TOO_LARGE: "MODBUS_REQUESTS_TOO_LARGE",
  MODBUS_INVALID_ADDRESS: "MODBUS_INVALID_ADDRESS",
  MODBUS_INVALID_VALUES: "MODBUS_INVALID_VALUES",
  MODBUS_INVALID_BODY: "MODBUS_INVALID_BODY",

  // --- Alerts ---
  ALERT_RULE_NOT_FOUND: "ALERT_RULE_NOT_FOUND",
  ALERT_VALIDATION_FAILED: "ALERT_VALIDATION_FAILED",
  ALERT_SMTP_INVALID: "ALERT_SMTP_INVALID",
  ALERT_SMTP_SEND_FAILED: "ALERT_SMTP_SEND_FAILED",

  // --- Device / stream ---
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  DEVICE_NOT_CAMERA: "DEVICE_NOT_CAMERA",
  DEVICE_RTSP_URL_MISSING: "DEVICE_RTSP_URL_MISSING",
  DEVICE_UNSUPPORTED_FEATURE: "DEVICE_UNSUPPORTED_FEATURE",
  DEVICE_NAME_REQUIRED: "DEVICE_NAME_REQUIRED",
  DEVICE_NAME_TOO_LONG: "DEVICE_NAME_TOO_LONG",
  DEVICE_TYPE_REQUIRED: "DEVICE_TYPE_REQUIRED",
  DEVICE_TYPE_INVALID: "DEVICE_TYPE_INVALID",
  DEVICE_CONFIG_REQUIRED: "DEVICE_CONFIG_REQUIRED",
  DEVICE_MODEL_ID_REQUIRED: "DEVICE_MODEL_ID_REQUIRED",
  DEVICE_MODEL_NOT_FOUND: "DEVICE_MODEL_NOT_FOUND",
  DEVICE_MODEL_TYPE_MISMATCH: "DEVICE_MODEL_TYPE_MISMATCH",
  DEVICE_LOGGING_CONFIG_INVALID: "DEVICE_LOGGING_CONFIG_INVALID",
  DEVICE_CONTROLLER_HOST_REQUIRED: "DEVICE_CONTROLLER_HOST_REQUIRED",
  DEVICE_CONTROLLER_PORT_REQUIRED: "DEVICE_CONTROLLER_PORT_REQUIRED",
  DEVICE_SENSOR_HOST_REQUIRED: "DEVICE_SENSOR_HOST_REQUIRED",
  DEVICE_SENSOR_PORT_REQUIRED: "DEVICE_SENSOR_PORT_REQUIRED",
  DEVICE_UNIT_ID_EXHAUSTED: "DEVICE_UNIT_ID_EXHAUSTED",
  DEVICE_DUPLICATE_CONNECTION: "DEVICE_DUPLICATE_CONNECTION",
  DEVICE_UPDATE_NO_FIELDS: "DEVICE_UPDATE_NO_FIELDS",
  DEVICE_LIST_FAILED: "DEVICE_LIST_FAILED",
  DEVICE_GET_FAILED: "DEVICE_GET_FAILED",
  DEVICE_CREATE_FAILED: "DEVICE_CREATE_FAILED",
  DEVICE_UPDATE_FAILED: "DEVICE_UPDATE_FAILED",
  DEVICE_DELETE_FAILED: "DEVICE_DELETE_FAILED",
  DEVICE_CAMERA_GROUPS_FAILED: "DEVICE_CAMERA_GROUPS_FAILED",
  DEVICE_CONFIG_INVALID: "DEVICE_CONFIG_INVALID",

  DEVICE_MODEL_NAME_REQUIRED: "DEVICE_MODEL_NAME_REQUIRED",
  DEVICE_MODEL_PORT_INVALID: "DEVICE_MODEL_PORT_INVALID",
  DEVICE_MODEL_UNIT_ID_INVALID: "DEVICE_MODEL_UNIT_ID_INVALID",
  DEVICE_MODEL_SENSOR_PARAMETERS_INVALID:
    "DEVICE_MODEL_SENSOR_PARAMETERS_INVALID",
  DEVICE_MODEL_REGISTER_TYPE_INVALID: "DEVICE_MODEL_REGISTER_TYPE_INVALID",
  DEVICE_MODEL_CATEGORY_CODE_INVALID: "DEVICE_MODEL_CATEGORY_CODE_INVALID",
  DEVICE_MODEL_TYPE_CHANGE_FORBIDDEN: "DEVICE_MODEL_TYPE_CHANGE_FORBIDDEN",
  DEVICE_MODEL_IN_USE: "DEVICE_MODEL_IN_USE",
  DEVICE_MODEL_UPDATE_NO_FIELDS: "DEVICE_MODEL_UPDATE_NO_FIELDS",
  DEVICE_MODEL_LIST_FAILED: "DEVICE_MODEL_LIST_FAILED",
  DEVICE_MODEL_GET_FAILED: "DEVICE_MODEL_GET_FAILED",
  DEVICE_MODEL_CREATE_FAILED: "DEVICE_MODEL_CREATE_FAILED",
  DEVICE_MODEL_UPDATE_FAILED: "DEVICE_MODEL_UPDATE_FAILED",
  DEVICE_MODEL_DELETE_FAILED: "DEVICE_MODEL_DELETE_FAILED",

  DEVICE_TYPE_LIST_FAILED: "DEVICE_TYPE_LIST_FAILED",

  DEVICE_CONNECTIVITY_RTSP_URL_INVALID: "DEVICE_CONNECTIVITY_RTSP_URL_INVALID",
  DEVICE_CONNECTIVITY_RTSP_TIMEOUT: "DEVICE_CONNECTIVITY_RTSP_TIMEOUT",
  DEVICE_CONNECTIVITY_RTSP_FAILED: "DEVICE_CONNECTIVITY_RTSP_FAILED",
  DEVICE_CONNECTIVITY_RTSP_RESPONSE_INVALID:
    "DEVICE_CONNECTIVITY_RTSP_RESPONSE_INVALID",
  DEVICE_CONNECTIVITY_MODBUS_CONFIG_INCOMPLETE:
    "DEVICE_CONNECTIVITY_MODBUS_CONFIG_INCOMPLETE",
  DEVICE_CONNECTIVITY_MODBUS_FAILED: "DEVICE_CONNECTIVITY_MODBUS_FAILED",
  DEVICE_CONNECTIVITY_ISAPI_CONFIG_INCOMPLETE:
    "DEVICE_CONNECTIVITY_ISAPI_CONFIG_INCOMPLETE",
  DEVICE_CONNECTIVITY_ISAPI_TIMEOUT: "DEVICE_CONNECTIVITY_ISAPI_TIMEOUT",
  DEVICE_CONNECTIVITY_CAMERA_RTSP_MISSING:
    "DEVICE_CONNECTIVITY_CAMERA_RTSP_MISSING",
  DEVICE_CONNECTIVITY_DEVICE_ID_INVALID:
    "DEVICE_CONNECTIVITY_DEVICE_ID_INVALID",

  MODBUS_DEVICE_CONFIG_REQUIRED: "MODBUS_DEVICE_CONFIG_REQUIRED",
  MODBUS_REGISTER_TYPE_UNSUPPORTED: "MODBUS_REGISTER_TYPE_UNSUPPORTED",
  MODBUS_CONNECTION_CLOSED: "MODBUS_CONNECTION_CLOSED",
  MODBUS_CONNECTION_INTERRUPTED: "MODBUS_CONNECTION_INTERRUPTED",
  MODBUS_CONNECTION_TIMEOUT: "MODBUS_CONNECTION_TIMEOUT",
  MODBUS_CONNECTION_REFUSED: "MODBUS_CONNECTION_REFUSED",
  MODBUS_CONNECTION_UNREACHABLE: "MODBUS_CONNECTION_UNREACHABLE",
  MODBUS_CONNECTION_FAILED: "MODBUS_CONNECTION_FAILED",
  MODBUS_READ_TIMEOUT: "MODBUS_READ_TIMEOUT",
  MODBUS_WRITE_TIMEOUT: "MODBUS_WRITE_TIMEOUT",
  MODBUS_HOST_REQUIRED: "MODBUS_HOST_REQUIRED",
  MODBUS_PORT_REQUIRED: "MODBUS_PORT_REQUIRED",
  MODBUS_UNIT_ID_REQUIRED: "MODBUS_UNIT_ID_REQUIRED",
  MODBUS_INVALID_LENGTH: "MODBUS_INVALID_LENGTH",

  // --- Access control / ISAPI ---
  ACCESS_CONTROL_NOT_DEVICE: "ACCESS_CONTROL_NOT_DEVICE",
  ACCESS_CONTROL_CONFIG_INCOMPLETE: "ACCESS_CONTROL_CONFIG_INCOMPLETE",
  ACCESS_CONTROL_ISAPI_INVALID_RESPONSE:
    "ACCESS_CONTROL_ISAPI_INVALID_RESPONSE",
  ACCESS_CONTROL_EMPLOYEE_NO_REQUIRED: "ACCESS_CONTROL_EMPLOYEE_NO_REQUIRED",
  ACCESS_CONTROL_CARD_NO_REQUIRED: "ACCESS_CONTROL_CARD_NO_REQUIRED",
  ACCESS_CONTROL_FINGER_DATA_REQUIRED: "ACCESS_CONTROL_FINGER_DATA_REQUIRED",
  ACCESS_CONTROL_FACE_IMAGE_REQUIRED: "ACCESS_CONTROL_FACE_IMAGE_REQUIRED",
  ACCESS_CONTROL_ABORTED: "ACCESS_CONTROL_ABORTED",

  // --- Vehicle access ISAPI (camera proxy) ---
  VEHICLE_ACCESS_NOT_CAMERA: "VEHICLE_ACCESS_NOT_CAMERA",
  VEHICLE_ACCESS_CONFIG_INCOMPLETE: "VEHICLE_ACCESS_CONFIG_INCOMPLETE",
  VEHICLE_ACCESS_ISAPI_INVALID_RESPONSE: "VEHICLE_ACCESS_ISAPI_INVALID_RESPONSE",
  VEHICLE_ACCESS_DEVICE_NOT_IN_SITE: "VEHICLE_ACCESS_DEVICE_NOT_IN_SITE",
  PLATE_ALREADY_ASSIGNED: "PLATE_ALREADY_ASSIGNED",

  // --- Location / zones ---
  LOCATION_ZONE_NOT_FOUND: "LOCATION_ZONE_NOT_FOUND",
  LOCATION_ZONE_NAME_REQUIRED: "LOCATION_ZONE_NAME_REQUIRED",
  LOCATION_ZONE_NAME_TOO_LONG: "LOCATION_ZONE_NAME_TOO_LONG",
  LOCATION_ZONE_NAME_DUPLICATE: "LOCATION_ZONE_NAME_DUPLICATE",
  LOCATION_ZONE_LIST_FAILED: "LOCATION_ZONE_LIST_FAILED",
  LOCATION_ZONE_GET_FAILED: "LOCATION_ZONE_GET_FAILED",
  LOCATION_ZONE_CREATE_FAILED: "LOCATION_ZONE_CREATE_FAILED",
  LOCATION_ZONE_UPDATE_FAILED: "LOCATION_ZONE_UPDATE_FAILED",
  LOCATION_ZONE_DELETE_FAILED: "LOCATION_ZONE_DELETE_FAILED",
  LOCATION_ZONE_DELETE_FORBIDDEN: "LOCATION_ZONE_DELETE_FORBIDDEN",

  LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",
  LOCATION_NAME_REQUIRED: "LOCATION_NAME_REQUIRED",
  LOCATION_NAME_TOO_LONG: "LOCATION_NAME_TOO_LONG",
  LOCATION_NAME_DUPLICATE: "LOCATION_NAME_DUPLICATE",
  LOCATION_GET_FAILED: "LOCATION_GET_FAILED",
  LOCATION_CREATE_FAILED: "LOCATION_CREATE_FAILED",
  LOCATION_UPDATE_FAILED: "LOCATION_UPDATE_FAILED",
  LOCATION_DELETE_FAILED: "LOCATION_DELETE_FAILED",

  LOCATION_SYSTEM_TYPE_REQUIRED: "LOCATION_SYSTEM_TYPE_REQUIRED",
  LOCATION_SYSTEM_TYPE_INVALID: "LOCATION_SYSTEM_TYPE_INVALID",
  LOCATION_SYSTEM_TYPE_DUPLICATE: "LOCATION_SYSTEM_TYPE_DUPLICATE",
  LOCATION_SYSTEM_NOT_FOUND: "LOCATION_SYSTEM_NOT_FOUND",
  LOCATION_DEVICE_NOT_FOUND: "LOCATION_DEVICE_NOT_FOUND",
  LOCATION_DEVICE_NOT_CONTROLLER: "LOCATION_DEVICE_NOT_CONTROLLER",

  // --- Personnel ---
  PERSONNEL_VALIDATION_FAILED: "PERSONNEL_VALIDATION_FAILED",
  PERSONNEL_PERSON_GROUP_NOT_FOUND: "PERSONNEL_PERSON_GROUP_NOT_FOUND",
  PERSONNEL_PERSON_NOT_FOUND: "PERSONNEL_PERSON_NOT_FOUND",
  PERSONNEL_FACE_UPLOAD_FILE_MISSING: "PERSONNEL_FACE_UPLOAD_FILE_MISSING",
  PERSONNEL_FACE_UPLOAD_INVALID_FILE_FORMAT:
    "PERSONNEL_FACE_UPLOAD_INVALID_FILE_FORMAT",
  PERSONNEL_FACE_UPLOAD_VALIDATION_FAILED:
    "PERSONNEL_FACE_UPLOAD_VALIDATION_FAILED",
  PERSONNEL_IMPORT_EXCEL_FILE_MISSING: "PERSONNEL_IMPORT_EXCEL_FILE_MISSING",
  PERSONNEL_IMPORT_VALIDATION_FAILED: "PERSONNEL_IMPORT_VALIDATION_FAILED",
  PERSONNEL_SYNC_JOB_NOT_FOUND: "PERSONNEL_SYNC_JOB_NOT_FOUND",
  PERSONNEL_SYNC_JOB_VALIDATION_FAILED: "PERSONNEL_SYNC_JOB_VALIDATION_FAILED",
  PERSONNEL_SYNC_UNKNOWN_STEP: "PERSONNEL_SYNC_UNKNOWN_STEP",
  PERSONNEL_SYNC_JOB_INVALID_REQUEST: "PERSONNEL_SYNC_JOB_INVALID_REQUEST",

  // --- Users / auth (service layer) ---
  USER_ROLE_INVALID: "USER_ROLE_INVALID",
  USER_STATUS_INVALID: "USER_STATUS_INVALID",
  USER_CREDENTIALS_REQUIRED: "USER_CREDENTIALS_REQUIRED",
  USER_PASSWORD_TOO_SHORT: "USER_PASSWORD_TOO_SHORT",
  USER_USERNAME_EXISTS: "USER_USERNAME_EXISTS",
  USER_USERNAME_TAKEN: "USER_USERNAME_TAKEN",
  USER_AUTH_FAILED: "USER_AUTH_FAILED",
  USER_ACCOUNT_INACTIVE: "USER_ACCOUNT_INACTIVE",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_FORBIDDEN_ROLE_STATUS: "USER_FORBIDDEN_ROLE_STATUS",
  USER_FORBIDDEN_UPDATE_OTHERS: "USER_FORBIDDEN_UPDATE_OTHERS",
  USER_FORBIDDEN_PASSWORD_OTHERS: "USER_FORBIDDEN_PASSWORD_OTHERS",
  USER_FORBIDDEN_PASSWORD_SELF: "USER_FORBIDDEN_PASSWORD_SELF",
  USER_FORBIDDEN_PASSWORD_TARGET: "USER_FORBIDDEN_PASSWORD_TARGET",
  USER_OLD_PASSWORD_REQUIRED: "USER_OLD_PASSWORD_REQUIRED",
  USER_FORBIDDEN_DELETE: "USER_FORBIDDEN_DELETE",
  USER_FORBIDDEN_DELETE_SELF: "USER_FORBIDDEN_DELETE_SELF",
  USER_FORBIDDEN_DELETE_ADMIN: "USER_FORBIDDEN_DELETE_ADMIN",
  USER_OLD_PASSWORD_INVALID: "USER_OLD_PASSWORD_INVALID",

  // --- Settings (service layer) ---
  SETTINGS_LIST_FAILED: "SETTINGS_LIST_FAILED",
  SETTINGS_GET_FAILED: "SETTINGS_GET_FAILED",
  SETTINGS_BATCH_GET_FAILED: "SETTINGS_BATCH_GET_FAILED",
  SETTINGS_UPSERT_FAILED: "SETTINGS_UPSERT_FAILED",
  SETTINGS_UPDATE_FAILED: "SETTINGS_UPDATE_FAILED",
  SETTINGS_DELETE_FAILED: "SETTINGS_DELETE_FAILED",

  // --- Environment ---
  ENVIRONMENT_BUCKET_INVALID: "ENVIRONMENT_BUCKET_INVALID",
  ENVIRONMENT_READINGS_LIST_FAILED: "ENVIRONMENT_READINGS_LIST_FAILED",
  ENVIRONMENT_READINGS_AGGREGATED_FAILED:
    "ENVIRONMENT_READINGS_AGGREGATED_FAILED",
  ENVIRONMENT_READING_REQUIRED: "ENVIRONMENT_READING_REQUIRED",

  // --- People counting ---
  PEOPLE_COUNTING_VALIDATION_FAILED: "PEOPLE_COUNTING_VALIDATION_FAILED",
  PEOPLE_COUNTING_OPERATION_FAILED: "PEOPLE_COUNTING_OPERATION_FAILED",

  // --- Alerts (service layer) ---
  ALERT_NOT_FOUND: "ALERT_NOT_FOUND",
  ALERT_CREATE_VALIDATION_FAILED: "ALERT_CREATE_VALIDATION_FAILED",
  ALERT_STATUS_INVALID: "ALERT_STATUS_INVALID",
  ALERT_OPERATION_FAILED: "ALERT_OPERATION_FAILED",
  ALERT_RULE_CREATE_FAILED: "ALERT_RULE_CREATE_FAILED",
  ALERT_RULE_UPDATE_FAILED: "ALERT_RULE_UPDATE_FAILED",
  ALERT_LINKAGE_ID_INVALID: "ALERT_LINKAGE_ID_INVALID",
  ALERT_LINKAGE_RULE_ID_INVALID: "ALERT_LINKAGE_RULE_ID_INVALID",
  ALERT_LINKAGE_NOT_FOUND: "ALERT_LINKAGE_NOT_FOUND",
  ALERT_LINKAGE_DO_TARGET_MISSING: "ALERT_LINKAGE_DO_TARGET_MISSING",
  ALERT_SYSTEM_UNKNOWN: "ALERT_SYSTEM_UNKNOWN",
  ALERT_SYSTEM_SNAPSHOT_UNSUPPORTED: "ALERT_SYSTEM_SNAPSHOT_UNSUPPORTED",
  ALERT_RULE_ALERT_TYPE_INVALID: "ALERT_RULE_ALERT_TYPE_INVALID",
  ALERT_RULE_BITKEY_INVALID: "ALERT_RULE_BITKEY_INVALID",
  ALERT_SOURCE_ID_NOT_FOUND: "ALERT_SOURCE_ID_NOT_FOUND",
  ALERT_RULE_NOT_AVAILABLE: "ALERT_RULE_NOT_AVAILABLE",
  ALERT_ERROR_TRACKER_UPSERT_FAILED: "ALERT_ERROR_TRACKER_UPSERT_FAILED",

  SMTP_HOST_REQUIRED: "SMTP_HOST_REQUIRED",
  SMTP_PORT_REQUIRED: "SMTP_PORT_REQUIRED",
  SMTP_SECURITY_INVALID: "SMTP_SECURITY_INVALID",

  LICENSE_FEATURE_KEY_REQUIRED: "LICENSE_FEATURE_KEY_REQUIRED",
  LICENSE_PLATFORM_API_BASE_URL_MISSING:
    "LICENSE_PLATFORM_API_BASE_URL_MISSING",
  LICENSE_PLATFORM_LICENSE_KEY_REQUIRED:
    "LICENSE_PLATFORM_LICENSE_KEY_REQUIRED",
  LICENSE_PLATFORM_DEVICE_FINGERPRINT_REQUIRED:
    "LICENSE_PLATFORM_DEVICE_FINGERPRINT_REQUIRED",

  MEDIAMTX_ADD_PATH_FAILED: "MEDIAMTX_ADD_PATH_FAILED",
  MEDIAMTX_ADD_PATH_REJECTED: "MEDIAMTX_ADD_PATH_REJECTED",
  MEDIAMTX_REMOVE_PATH_FAILED: "MEDIAMTX_REMOVE_PATH_FAILED",
  MEDIAMTX_CONFIG_NOT_FOUND: "MEDIAMTX_CONFIG_NOT_FOUND",

  MONITOR_MODBUS_READ_FAILED: "MONITOR_MODBUS_READ_FAILED",
  MONITOR_TASK_INVALID: "MONITOR_TASK_INVALID",
  MONITOR_FACTORY_CONFIG_INVALID: "MONITOR_FACTORY_CONFIG_INVALID",

  EXTERNAL_DATA_QUERY_FAILED: "EXTERNAL_DATA_QUERY_FAILED",
  EXTERNAL_DATA_COUNT_FAILED: "EXTERNAL_DATA_COUNT_FAILED",

  ACCESS_CONTROL_ISAPI_DIGEST_CHALLENGE_EXPECTED:
    "ACCESS_CONTROL_ISAPI_DIGEST_CHALLENGE_EXPECTED",
  ACCESS_CONTROL_ISAPI_AUTH_UNSUPPORTED:
    "ACCESS_CONTROL_ISAPI_AUTH_UNSUPPORTED",

  BACKUP_DELETE_AFTER_SUCCESS_FAILED: "BACKUP_DELETE_AFTER_SUCCESS_FAILED",

  YSCP_FILE_NOT_FOUND: "YSCP_FILE_NOT_FOUND",
  YSCP_PERSON_INFO_FAILED: "YSCP_PERSON_INFO_FAILED",
  YSCP_PERSON_PICTURE_FAILED: "YSCP_PERSON_PICTURE_FAILED",
  YSCP_RESPONSE_PARSE_FAILED: "YSCP_RESPONSE_PARSE_FAILED",

  MULTIMEDIA_MODBUS_READ_FAILED: "MULTIMEDIA_MODBUS_READ_FAILED",
};
